name: Issue - Labeling
on:
  workflow_dispatch:
  issues:
      types: ['opened']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Renato66/auto-label@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-comments: true
          labels-synonyms: '{
            "Priority: Low":["Low"],
            "Priority: Medium":["Medium"],
            "Priority: High":["High"],
            "Priority: Critical":["Critical"],
            "Area: Admin":["[X] Admin"],
            "Area: Assets":["[X] Assets"],
            "Area: Install":["[X] Install"],
            "Area: Plugins":["[X] Plugins"],
            "Area: System":["[X] System"],
            "Area: Templates":["[X] Templates"],
            "Area: Tools":["[X] Tools"],
            "Type: Enhancement":["Enhancement"],
            "Type: Missing Content":["Missing Content"]
          }'
          default-labels: '["Status: Pending Test"]'
