name: PHP Linting
on:
    pull_request:
        branches: [master]
    push:
        branches: [master]

jobs:
    phplint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: overtrue/phplint@7.4
              with:
                  path: .
                  options: --exclude="system/libs/polyfill-mbstring/bootstrap80.php"
